import { DonationRecord, Language, TranslationSet } from "./types";

export const COLORS = ['#009640', '#F59E0B', '#10B981', '#3B82F6', '#6366F1', '#EC4899', '#8B5CF6', '#EF4444'];

export const THEME_COLORS: Record<string, string> = {
  'Orphelins': '#F59E0B', // Amber
  'Eau potable': '#3B82F6', // Blue
  'Urgences': '#EF4444', // Red
  'Santé': '#10B981', // Emerald
  'Faim': '#8B5CF6', // Violet
  'Education': '#6366F1', // Indigo
  'Fonds general': '#64748B' // Slate
};

export const TRANSLATIONS: Record<Language, TranslationSet> = {
  fr: {
    title: "Muslim Hands France",
    subtitle: "Tableau de Bord",
    import: "Importer",
    change: "Changer",
    aiAssistant: "Assistant IA",
    reportMode: "Mode Rapport",
    period: "Période",
    totalCollected: "Total Collecté",
    totalDonations: "Nombre de Dons",
    avgDonation: "Don Moyen",
    topCause: "Top Cause",
    deepDiveTitle: "Analyse Détaillée par Cause",
    deepDiveSubtitle: "Explorez les sous-types de projets et l'évolution mensuelle.",
    causeSelected: "Cause Sélectionnée",
    breakdown: "Répartition",
    monthlyTrend: "Évolution Mensuelle",
    globalView: "Vue Globale par Thème",
    fundType: "Type de Fonds",
    topDestinations: "Top Destinations (Localité)",
    topProjects: "Top Projets Financés",
    noData: "Aucune donnée trouvée",
    noDataSub: "Veuillez vérifier vos filtres ou importer un fichier CSV.",
    reset: "Réinitialiser",
    aiWelcome: "Bonjour ! Je suis votre assistant de données. Posez-moi une question sur les dons, les tendances ou les projets.",
    aiPlaceholder: "Posez votre question ici...",
    aiThinking: "Analyse en cours...",
    funnel: "Entonnoir",
    bars: "Barres",
    subtextKpi1: "Sur la période sélectionnée",
    subtextKpi2: "Transactions individuelles",
    subtextKpi3: "Par transaction",
    subtextKpi4: "Montant le plus élevé",
    exportJpg: "Télécharger en JPG",
    analysis: "Analyse Rapide",
    story: "Générer Histoire",
    chat: "Discussion",
    send: "Envoyer",
    quickPrompt1: "Analyse les tendances",
    quickPrompt2: "Top pays bénéficiaires ?",
    quickPrompt3: "Email de remerciement",
  },
  en: {
    title: "Muslim Hands France",
    subtitle: "Donor Dashboard",
    import: "Import",
    change: "Change",
    aiAssistant: "AI Assistant",
    reportMode: "Report Mode",
    period: "Period",
    totalCollected: "Total Collected",
    totalDonations: "Total Donations",
    avgDonation: "Avg Donation",
    topCause: "Top Cause",
    deepDiveTitle: "Deep Dive Analysis",
    deepDiveSubtitle: "Explore project sub-types and monthly trends.",
    causeSelected: "Selected Cause",
    breakdown: "Breakdown",
    monthlyTrend: "Monthly Trend",
    globalView: "Global View by Theme",
    fundType: "Fund Type",
    topDestinations: "Top Destinations",
    topProjects: "Top Funded Projects",
    noData: "No data found",
    noDataSub: "Please check your filters or upload a CSV file.",
    reset: "Reset",
    aiWelcome: "Hello! I am your data assistant. Ask me anything about donations, trends, or projects.",
    aiPlaceholder: "Ask your question here...",
    aiThinking: "Analyzing...",
    funnel: "Funnel",
    bars: "Bars",
    subtextKpi1: "During selected period",
    subtextKpi2: "Individual transactions",
    subtextKpi3: "Per transaction",
    subtextKpi4: "Highest amount",
    exportJpg: "Download JPG",
    analysis: "Quick Analysis",
    story: "Generate Story",
    chat: "Chat",
    send: "Send",
    quickPrompt1: "Analyze trends",
    quickPrompt2: "Top beneficiary countries?",
    quickPrompt3: "Thank you email",
  },
  ur: {
    title: "مسلم ہینڈز فرانس",
    subtitle: "ڈیش بورڈ",
    import: "درآمد کریں",
    change: "تبدیل کریں",
    aiAssistant: "AI مددگار",
    reportMode: "رپورٹ موڈ",
    period: "مدت",
    totalCollected: "کل جمع شدہ رقم",
    totalDonations: "کل عطیات",
    avgDonation: "اوسط عطیہ",
    topCause: "سب سے بڑی وجہ",
    deepDiveTitle: "تفصیلی تجزیہ",
    deepDiveSubtitle: "پروجیکٹ کی اقسام اور ماہانہ رجحانات دیکھیں۔",
    causeSelected: "منتخب کردہ وجہ",
    breakdown: "تقسیم",
    monthlyTrend: "ماہانہ رجحان",
    globalView: "موضوع کے لحاظ سے جائزہ",
    fundType: "فنڈ کی قسم",
    topDestinations: "نمایاں مقامات",
    topProjects: "نمایاں پروجیکٹس",
    noData: "کوئی ڈیٹا نہیں ملا",
    noDataSub: "براہ کرم فلٹرز چیک کریں یا CSV فائل اپ لوڈ کریں۔",
    reset: "ری سیٹ کریں",
    aiWelcome: "السلام علیکم! میں آپ کا ڈیٹا اسسٹنٹ ہوں۔ آپ مجھ سے عطیات، رجحانات یا پروجیکٹس کے بارے میں سوال پوچھ سکتے ہیں۔",
    aiPlaceholder: "اپنا سوال یہاں لکھیں...",
    aiThinking: "تجزیہ جاری ہے...",
    funnel: "فنل",
    bars: "بارز",
    subtextKpi1: "منتخب مدت کے دوران",
    subtextKpi2: "انفرادی لین دین",
    subtextKpi3: "فی لین دین",
    subtextKpi4: "سب سے زیادہ رقم",
    exportJpg: "JPG ڈاؤن لوڈ کریں",
    analysis: "فوری تجزیہ",
    story: "کہانی لکھیں",
    chat: "گفتگو",
    send: "بھیجیں",
    quickPrompt1: "رجحانات کا تجزیہ کریں",
    quickPrompt2: "کون سے ممالک سر فہرست ہیں؟",
    quickPrompt3: "شکریہ کا ای میل لکھیں",
  }
};

export const SAMPLE_DATA: DonationRecord[] = [
    { "Donation Date": "1/1/25", "Amount": "39", "Thème": "Orphelins", "Requête": "Sadaqa", "Localité": "Sénégal", "Account Postal Region": "Val-de-Marne", "Allocation Summary": "Sponsorship - Orphelin", "Income Type": "Regular Donation" },
    { "Donation Date": "1/1/25", "Amount": "10", "Thème": "Eau potable", "Requête": "Sadaqa", "Localité": "Où le plus utile", "Account Postal Region": "Essonne", "Allocation Summary": "Fonds pour l'Eau", "Income Type": "Regular Donation" },
    { "Donation Date": "1/1/25", "Amount": "39", "Thème": "Orphelins", "Requête": "Sadaqa", "Localité": "Pakistan", "Account Postal Region": "Val-d'Oise", "Allocation Summary": "Sponsorship - Orphelin", "Income Type": "Regular Donation" },
    { "Donation Date": "26/3/25", "Amount": "5", "Thème": "Fonds general", "Requête": "Sadaqa", "Localité": "Où le plus utile", "Account Postal Region": "Essonne", "Allocation Summary": "GG - Village Espoir (Forage)", "Income Type": "Single Donation" },
    { "Donation Date": "26/3/25", "Amount": "10", "Thème": "Fonds general", "Requête": "Sadaqa", "Localité": "Où le plus utile", "Account Postal Region": "Essonne", "Allocation Summary": "GG - Village Espoir (Forage)", "Income Type": "Single Donation" },
    { "Donation Date": "6/12/25", "Amount": "0.50", "Thème": "Urgences", "Requête": "Sadaqa", "Localité": "Palestine", "Account Postal Region": "Alpes-Maritimes", "Allocation Summary": "Fonds Palestine", "Income Type": "Single Donation" },
    { "Donation Date": "6/12/25", "Amount": "5.00", "Thème": "Eau potable", "Requête": "Sadaqa", "Localité": "Où le plus utile", "Account Postal Region": "Paris", "Allocation Summary": "Fonds pour l'Eau", "Income Type": "Single Donation" },
    { "Donation Date": "15/1/25", "Amount": "220", "Thème": "Eau potable", "Requête": "Sadaqa", "Localité": "Niger", "Account Postal Region": "Toulouse", "Allocation Summary": "Pompe Manuelle", "Income Type": "Single Donation" },
    { "Donation Date": "10/2/25", "Amount": "100", "Thème": "Urgences", "Requête": "Zakat", "Localité": "Palestine", "Account Postal Region": "Paris", "Allocation Summary": "Fonds Palestine", "Income Type": "Single Donation" },
    { "Donation Date": "5/3/25", "Amount": "770", "Thème": "Eau potable", "Requête": "Sadaqa Jariya", "Localité": "Mali", "Account Postal Region": "Lyon", "Allocation Summary": "Puits Communautaire", "Income Type": "Single Donation" },
    { "Donation Date": "1/4/25", "Amount": "500", "Thème": "Urgences", "Requête": "Zakat", "Localité": "Palestine", "Account Postal Region": "Marseille", "Allocation Summary": "Urgence Gaza", "Income Type": "Single Donation" },
    { "Donation Date": "15/4/25", "Amount": "150", "Thème": "Faim", "Requête": "Fidya", "Localité": "Yemen", "Account Postal Region": "Val-de-Marne", "Allocation Summary": "Colis Alimentaire", "Income Type": "Single Donation" },
    { "Donation Date": "10/9/25", "Amount": "900", "Thème": "Eau potable", "Requête": "Sadaqa Jariya", "Localité": "Pakistan", "Account Postal Region": "Strasbourg", "Allocation Summary": "Grand Puits", "Income Type": "Single Donation" },
];